### ISSUE TITLE
在main.js中注册直接报错

### ISSUE THREAD

**Issue by happy2277** [Alfred-Skyblue/v-scale-screen#12]
vue2.6.10
v-scale-screen 2.2.0
![image](https://github.com/Alfred-Skyblue/v-scale-screen/assets/22534193/6e8a91e4-3bdc-4b4b-8712-23e5cc3ae422)

**Comment by Alfred-Skyblue** [comment]
https://github.com/Alfred-Skyblue/v-scale-screen/blob/v3.0/README.zh_CN.md

vue2.6使用1.x版本
