### ISSUE TITLE
vite项目elementUI dialog不随容器变化

### ISSUE THREAD

**Issue by renjieyao** [Alfred-Skyblue/v-scale-screen#5]
麻烦大佬帮忙看看，el-dialog没有收到scale属性的影响，还是正常缩放，配置信息如下
"devDependencies": {
        "less": "^4.1.3",
        "v-scale-screen": "1.0.2",
        "vite": "2.9.15",
        "vite-plugin-vue2": "^1.9.3"
    },
    "dependencies": {
        "@riophae/vue-treeselect": "^0.4.0",
        "axios": "^0.27.2",
        "cad-project": "^1.2.7",
        "core-js": "3.23.4",
        "echarts": "^4.8.0",
        "element-ui": "^2.15.6",
        "less-loader": "7.3.0",
        "moment": "^2.29.4",
        "vue": "2.6.10",
        "vue-router": "^3.2.0",
        "vue-template-compiler": "2.6.10"
    }

**Comment by Alfred-Skyblue** [comment]
dialog默认会渲染到body上面，你需要将dialog渲染到你自适应的区域，才可以适应到scale属性

**Comment by renjieyao** [comment]
> dialog默认会渲染到body上面，你需要将dialog渲染到你自适应的区域，才可以适应到scale属性

但是去掉append-to-body的话那个遮罩层会在dialog上面，就是vite项目是这种情况，webpack的项目加append-to-body是可以的

**Comment by Alfred-Skyblue** [comment]
样式的问题调整一下zindex就可以里

**Comment by renjieyao** [comment]
> 样式的问题调整一下zindex就可以里

去掉了v-madal这个样式类，本来他多出来了一个遮罩层
